### ISSUE TITLE
Debian/Raspbian installation problem: phantomjs 404 not found

### ISSUE THREAD

**Issue by tometty** [vecna/trackmap#39]
When I run **./fetch_phantomjs.sh** I get the following error:

>pi@raspberrypi ~/trackmap/trackmap-master $ ./fetch_phantomjs.sh
--2015-01-04 14:31:57--  https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-armv6l.tar.bz2
Resolving bitbucket.org (bitbucket.org)... 131.103.20.167, 131.103.20.168
Connecting to bitbucket.org (bitbucket.org)|131.103.20.167|:443... connected.
HTTP request sent, awaiting response... 404 NOT FOUND
2015-01-04 14:32:04 ERROR 404: NOT FOUND.
>
>tar: phantomjs-1.9.8-linux-armv6l.tar.bz2: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
ln: failed to create symbolic link `phantom-1.9.8': File exists
pi@raspberrypi ~/trackmap/trackmap-master $

How do I go on from here?

**Comment by vecna** [comment]
In fact, the place where I'm fetching Phantom.JS supports only i386 and x86_64, I've found this repository https://github.com/aeberhardo/phantomjs-linux-armv6l but I'll ask to you to follow that guide, and then put a symlink called 'phantom-1.9.8' pointing to the appropriate binary. sorry for the trouble!

**Comment by ourari** [comment]
No worries. I followed your suggestions and the test run is running as I type this. Thank you! 

There's a lot of errors though. I'm using the new medialist for the Netherlands. The errors all look like this:
>output/publication.tld [Errno 2] No such file or directory: 'output/publication.tld/__urls'
>Total or partial failure with pubication.tld # retry

and then later on it didn't work on the second try either.

The test run has now concluded and it lists all the sites, 122 in total, it was unable to read and subsequently skipped. At the end it reads:

>Traceback (most recent call last):
>  File ".perform_analysis.py", line 1060, in <module>
>    main()
>  File "./perform_analysis.py", line 846, in main
>    assert [included_url_dict, "No url included after phantom scraping and collection !?"
>AssertionError: No url includd after phanom scraping and collection !?

When I try to run it again, it mentions a backlog and shows the same list.

**Comment by vecna** [comment]
The fact that everything is failing, is a network or a software issue. please try to run

    $ ./phantom-1.9.8 collect_included_url.js http://www.omroepgelderland.nl /tmp

and I'm looping over any website submitted by you guys, I'll update some changes ASAP.

**Comment by ourari** [comment]
I did what you suggested, this was the result:  
  
>TypeError: 'undefined' is not a function (evaluating 'window.addEvent')  
>  
>	http://omroepgelderland.nl/design/channel/tv/js/ieHover.js:16
>Error: Syntax error, unrecognized expression: [nodeName=jwplayer:sharing.link]
>  
>	http://omroepgelderland.nl/design/channel/tv/js/jquery.js:4
>	http://omroepgelderland.nl/design/channel/tv/js/jquery.js:4 in ft
>	http://omroepgelderland.nl/design/channel/tv/js/jquery.js:4 in wt
>	http://omroepgelderland.nl/design/channel/tv/js/jquery.js:4 in st
>	http://omroepgelderland.nl/design/channel/tv/js/jquery.js:4
>	http://omroepgelderland.nl/:453
>	http://omroepgelderland.nl/design/channel/tv/js/jquery.js:3
>	http://omroepgelderland.nl/design/channel/tv/js/jquery.js:3
>	http://omroepgelderland.nl/:455
>	http://omroepgelderland.nl/design/channel/tv/js/jquery.js:3
>	http://omroepgelderland.nl/design/channel/tv/js/jquery.js:3
>	http://omroepgelderland.nl/design/channel/tv/js/jquery.js:5  in k
>	http://omroepgelderland.nl/design/channel/tv/js/jquery.js:5
