### ISSUE TITLE
The .tar.gz file is created with a bad filename, which leads to problems.

### ISSUE THREAD

**Issue by krokodilerian** [vecna/trackmap#56]
First, while building the results I got error "file not found", as it was trying to create "results-verified_media/bulgaria.tar.gz", and there was no "results-verified_media" directory. I thought that it wasn't getting created for some reason, so I created it manually and reran the script, which was able to create the tar.gz file, but then unable to submit it, giving me the error "Expected not more than 28 byte here". It left the .tar.gz file, which I was able to submit with the script by copying it in the same directory and not giving it the full path (e.g. the filename was less that 28 characters).

I was unable to see why the name of the tar.gz file was results-verified_media/bulgaria.tar.gz insteaf of results-bulgaria.tar.gz, as the code looks OK to me.

**Comment by vecna** [comment]
mistakes in master, my bad. will be solved tomorrow. delete your current tar.gz. I will not be able to parse it ..

**Comment by vecna** [comment]
I'm addressing this issue now (I'm also completing a new series of patches useful to other visualisation)

**Comment by vecna** [comment]
the error was: the country name is changed and contain a part of the media directory. verified_media/ in your case, special_media/ in the new case I'm dealing with.

**Comment by vecna** [comment]
Sadly I was changing the format in the meantime, so you're output are inconsistent, my bad.

    with file(os.path.join(self.outputdir, mediadumpdir, 'request'), 'r') as f:
IOError: [Errno 2] No such file or directory: '../decompr/370-BUL/theglobeandmail.com_43/request'

is missing a new file that now I'm expecting, and I've marked already the new version as '6'. I can import them, just, if tomorrow you'll relaunch the script will be easier :) 

**tomorrow** or after, please, today I'm overbusy fixing other stuff :P

**Comment by krokodilerian** [comment]
@vecna, np, I'll keep an eye on the commits here and rerun it when I see the update.
