### ISSUE TITLE
Query on Maintanance

### ISSUE THREAD

**Issue by RupeshGoud** [vecna/trackmap#74]
Is this project is not maintained anymore?
What are the better alternatives ways to find the trackers present on a website?
Any implementing idea or APIs already implemented, please?

**Comment by vecna** [comment]
Hi, the project https://trackography.org is not maintain. An evolution of the same is the repository: [vecna/invi.sible.link](https://github.com/vecna/invi.sible.link) 

invi.sible.link implement a more flexible and reusable backend, but a weaker frontend. It is fully based on API who permits to create list of sites, have them analyze periodically, or just submit new websites and get results.
